(() => {
  'use strict';
  const dictionaries = {
    en: { 'الرئيسية':'Home','من نحن':'About','اتصل بنا':'Contact','الخصوصية':'Privacy','الشروط':'Terms','الملف الشخصي':'Profile','مكافأة يومية':'Daily reward','سحب المكافأة':'Reward draw','استرداد الاستهلاك':'Consumption recovery','تسجيل الخروج':'Sign out','تسجيل الدخول':'Sign in','العودة':'Back','العربية':'Arabic','ترجمة إلى العربية':'Translate to Arabic','عرض النص الأصلي':'Show original','عرض الترجمة':'Show translation','جارٍ الترجمة…':'Translating…','إعادة المحاولة':'Retry','حظًا موفقًا':'Good luck','الخزنة ممتلئة':'Vault is full','غير متاح الآن':'Unavailable','تعذر تحميل الشريط حاليًا':'The bar could not be loaded','أخبار الدولة':'Country news','لغة أجنبية':'Foreign language','لغة عربية':'Arabic language','اسحب الآن':'Spin now','رصيد الخزنة':'Vault balance','استهلاكك داخل الموقع':'Your site usage','استرداد الرصيد':'Redeem balance','بدء الاسترداد':'Start redemption','متاح عند اكتمال الشريط':'Available when full','من أصل':'of','فتحة':'slots' },
    ja: { 'الرئيسية':'ホーム','من نحن':'概要','اتصل بنا':'お問い合わせ','الخصوصية':'プライバシー','الشروط':'利用規約','الملف الشخصي':'プロフィール','مكافأة يومية':'デイリー報酬','سحب المكافأة':'報酬抽選','استرداد الاستهلاك':'利用回復','تسجيل الخروج':'ログアウト','تسجيل الدخول':'ログイン','العودة':'戻る','العربية':'アラビア語','ترجمة إلى العربية':'アラビア語に翻訳','عرض النص الأصلي':'原文を表示','عرض الترجمة':'翻訳を表示','جارٍ الترجمة…':'翻訳中…','إعادة المحاولة':'再試行','حظًا موفقًا':'幸運を','الخزنة ممتلئة':'保管庫が満杯です','غير متاح الآن':'現在利用できません','تعذر تحميل الشريط حاليًا':'バーを読み込めませんでした','لغة أجنبية':'外国語','لغة عربية':'アラビア語','اسحب الآن':'回す','رصيد الخزنة':'保管庫残高','استهلاكك داخل الموقع':'サイト利用状況','استرداد الرصيد':'残高を回復','بدء الاسترداد':'回復を開始' },
    fr: { 'الرئيسية':'Accueil','من نحن':'À propos','اتصل بنا':'Contact','الخصوصية':'Confidentialité','الشروط':'Conditions','الملف الشخصي':'Profil','مكافأة يومية':'Récompense quotidienne','سحب المكافأة':'Tirage au sort','استرداد الاستهلاك':'Récupération de consommation','تسجيل الخروج':'Se déconnecter','تسجيل الدخول':'Se connecter','العودة':'Retour','العربية':'Arabe','ترجمة إلى العربية':'Traduire en arabe','عرض النص الأصلي':'Voir l’original','عرض الترجمة':'Voir la traduction','جارٍ الترجمة…':'Traduction…','إعادة المحاولة':'Réessayer','حظًا موفقًا':'Bonne chance','الخزنة ممتلئة':'La réserve est pleine','غير متاح الآن':'Indisponible','لغة أجنبية':'Langue étrangère','لغة عربية':'Langue arabe' },
    de: { 'الرئيسية':'Startseite','من نحن':'Über uns','اتصل بنا':'Kontakt','الخصوصية':'Datenschutz','الشروط':'Bedingungen','الملف الشخصي':'Profil','مكافأة يومية':'Tagesbelohnung','سحب المكافأة':'Belohnung ziehen','استرداد الاستهلاك':'Verbrauchsrückgewinnung','تسجيل الخروج':'Abmelden','تسجيل الدخول':'Anmelden','العودة':'Zurück','العربية':'Arabisch','ترجمة إلى العربية':'Ins Arabische übersetzen','عرض النص الأصلي':'Original anzeigen','عرض الترجمة':'Übersetzung anzeigen','جارٍ الترجمة…':'Übersetzung…','إعادة المحاولة':'Erneut versuchen','حظًا موفقًا':'Viel Glück','الخزنة ممتلئة':'Tresor ist voll','غير متاح الآن':'Nicht verfügbar','لغة أجنبية':'Fremdsprache','لغة عربية':'Arabische Sprache' },
    es: { 'الرئيسية':'Inicio','من نحن':'Sobre nosotros','اتصل بنا':'Contacto','الخصوصية':'Privacidad','الشروط':'Condiciones','الملف الشخصي':'Perfil','مكافأة يومية':'Recompensa diaria','سحب المكافأة':'Sorteo de recompensa','استرداد الاستهلاك':'Recuperación de consumo','تسجيل الخروج':'Cerrar sesión','تسجيل الدخول':'Iniciar sesión','العودة':'Volver','العربية':'Árabe','ترجمة إلى العربية':'Traducir al árabe','عرض النص الأصلي':'Ver original','عرض الترجمة':'Ver traducción','جارٍ الترجمة…':'Traduciendo…','إعادة المحاولة':'Reintentar','حظًا موفقًا':'Buena suerte','الخزنة ممتلئة':'La bóveda está llena','غير متاح الآن':'No disponible','لغة أجنبية':'Idioma extranjero','لغة عربية':'Idioma árabe' },
    tr: { 'الرئيسية':'Ana sayfa','من نحن':'Hakkımızda','اتصل بنا':'İletişim','الخصوصية':'Gizlilik','الشروط':'Koşullar','الملف الشخصي':'Profil','مكافأة يومية':'Günlük ödül','سحب المكافأة':'Ödül çekilişi','استرداد الاستهلاك':'Tüketim iadesi','تسجيل الخروج':'Çıkış yap','تسجيل الدخول':'Giriş yap','العودة':'Geri','العربية':'Arapça','ترجمة إلى العربية':'Arapçaya çevir','عرض النص الأصلي':'Orijinali göster','عرض الترجمة':'Çeviriyi göster','جارٍ الترجمة…':'Çevriliyor…','إعادة المحاولة':'Tekrar dene','حظًا موفقًا':'Bol şans','الخزنة ممتلئة':'Kasa dolu','غير متاح الآن':'Kullanılamıyor','لغة أجنبية':'Yabancı dil','لغة عربية':'Arapça' },
    nl: { 'الرئيسية':'Home','من نحن':'Over ons','اتصل بنا':'Contact','الخصوصية':'Privacy','الشروط':'Voorwaarden','الملف الشخصي':'Profiel','مكافأة يومية':'Dagelijkse beloning','سحب المكافأة':'Beloning trekken','استرداد الاستهلاك':'Verbruiksherstel','تسجيل الخروج':'Uitloggen','تسجيل الدخول':'Inloggen','العودة':'Terug','العربية':'Arabisch','ترجمة إلى العربية':'Vertalen naar Arabisch','عرض النص الأصلي':'Origineel tonen','عرض الترجمة':'Vertaling tonen','جارٍ الترجمة…':'Vertalen…','إعادة المحاولة':'Opnieuw proberen','حظًا موفقًا':'Veel succes','الخزنة ممتلئة':'Kluis is vol','غير متاح الآن':'Niet beschikbaar','لغة أجنبية':'Vreemde taal','لغة عربية':'Arabische taal' }
  };
  const skip = el => el.closest?.('script,style,pre,code,[data-no-translate]');
  const translated = new WeakSet();
  const apply = () => { const fullLang=String(document.documentElement.dataset.mirsadLocale || 'ar'); const lang=fullLang.split('-')[0]; const map=dictionaries[lang]||{}; document.documentElement.dir=['ar','fa','he','ur'].includes(lang)?'rtl':'ltr'; document.documentElement.lang=fullLang; const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT); const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode); const pending=[]; nodes.forEach(node=>{if(translated.has(node)||skip(node.parentElement))return;const value=node.nodeValue.trim();if(!value||value.length>180)return;if(map[value]){node.nodeValue=node.nodeValue.replace(value,map[value]);translated.add(node);}else if(lang!=='ar'&&/\p{L}/u.test(value)){pending.push({node,source:value});}}); document.querySelectorAll('[aria-label],[title],[placeholder]').forEach(el=>{if(skip(el))return;['aria-label','title','placeholder'].forEach(attr=>{const value=el.getAttribute(attr);if(map[value])el.setAttribute(attr,map[value]);});}); if(!pending.length||window.__mirsadUiTranslationInFlight||lang==='ar')return; window.__mirsadUiTranslationInFlight=true; const sources=[...new Map(pending.map(x=>[x.source,x])).values()].slice(0,60).map(x=>x.source); fetch('https://dndlkenyfymlrjnslyzb.supabase.co/functions/v1/mirsad-translate-ui',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target_language:fullLang,strings:sources}),credentials:'omit',cache:'no-store'}).then(r=>r.ok?r.json():null).then(result=>{const mapAI=new Map((result?.translations||[]).map(x=>[x.source,x.translation]));pending.forEach(({node,source})=>{const value=mapAI.get(source);if(value&&node.isConnected){node.nodeValue=node.nodeValue.replace(source,value);translated.add(node);}});}).catch(()=>{}).finally(()=>{window.__mirsadUiTranslationInFlight=false;}); };
  window.addEventListener('mirsad:locale-detected', apply); new MutationObserver(()=>{ if(document.documentElement.dataset.mirsadLocale) apply(); }).observe(document.body,{childList:true,subtree:true}); apply();
})();
