(() => {
  'use strict';
  const CONFIG = { url: 'https://dndlkenyfymlrjnslyzb.supabase.co', key: 'sb_publishable_C92j3hFC-qVem_ncKHDf9Q_Ew970XUx' };
  const rail = document.getElementById('rapidNews');
  const list = document.getElementById('rapidNewsList');
  const badge = document.getElementById('rapidNewsBadge');
  const status = document.getElementById('rapidNewsStatus');
  const toggle = document.getElementById('rapidNewsToggle');
  const more = document.getElementById('rapidNewsMore');
  const all = document.getElementById('rapidNewsAll');
  if (!rail || !list || !badge || !toggle || !more || !all || !window.supabase?.createClient) return;
  const sb = window.supabase.createClient(CONFIG.url, CONFIG.key, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: false } });
  const escapeHtml = (value) => String(value || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const cleanRichText = (value) => MirsadText.normalize(value);
  const relative = (value) => { const time = new Date(value || 0).getTime(); if (!Number.isFinite(time)) return ''; const mins = Math.round((time - Date.now()) / 60000); const formatter = new Intl.RelativeTimeFormat('ar', { numeric: 'auto' }); return Math.abs(mins) < 60 ? formatter.format(mins, 'minute') : formatter.format(Math.round(mins / 60), 'hour'); };
  let opened = false;
  let currentUser = false;
  let channel = null;
  let timer = null;
  let currentRows = [];
  let visibleCount = 3;
  const setBadge = (count) => { badge.textContent = count > 99 ? '99+' : String(Math.max(0, count)); badge.hidden = count <= 0; };
  const pinIcon = '<span class="rapid-news__pin" title="خبر مهم مثبت" aria-label="خبر مهم مثبت"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.7 3.5 20.5 9l-2.2 2.2-1.1-.3-3.1 3.1.5 3.2-1.5 1.5-3.8-3.8-4.6 4.6-.9-.9 4.6-4.6-3.8-3.8 1.5-1.5 3.2.5 3.1-3.1-.3-1.1 2.2-2.2Z"/></svg></span>';
  const captureTime = (row) => new Date(row.published_at || row.received_at || 0).getTime() || 0;
  const publicationTime = (row) => new Date(row.published_at || row.received_at || 0).getTime() || 0;
  const PIN_MAX_AGE_MS = 100 * 60 * 60 * 1000;
  const render = (rows) => { const chronological = [...(rows || [])].sort((a, b) => captureTime(b) - captureTime(a)); const now = Date.now(); const pinnedRows = chronological.filter((row) => Number(row.importance_score || 0) >= 60 && now - publicationTime(row) <= PIN_MAX_AGE_MS).slice(0, 4); const pinnedIds = new Set(pinnedRows.map((row) => row.id)); const ordered = [...pinnedRows, ...chronological.filter((row) => !pinnedIds.has(row.id))]; currentRows = ordered; visibleCount = Math.min(Math.max(visibleCount, Math.max(3, pinnedRows.length)), ordered.length); const visible = ordered.slice(0, visibleCount); list.innerHTML = visible.length ? visible.map((row) => { const pinned = pinnedIds.has(row.id); const publishedAt = row.published_at || row.received_at; return `<article class="rapid-news__item${pinned ? ' is-pinned' : ''}">${pinned ? pinIcon : ''}<div class="rapid-news__meta"><span>${escapeHtml(row.source_name)}</span><time datetime="${escapeHtml(publishedAt)}">نُشر ${escapeHtml(relative(publishedAt))}</time></div><h3>${escapeHtml(cleanRichText(row.headline))}</h3><p>${escapeHtml(cleanRichText(row.summary))}</p><a href="${escapeHtml(row.source_url)}" target="_blank" rel="noopener noreferrer">المصدر الأصلي</a></article>`; }).join('') : '<p class="rapid-news__empty">لا توجد أخبار ملتقطة حاليًا.</p>'; more.hidden = visibleCount >= ordered.length; all.hidden = visibleCount >= ordered.length; };
  const load = async () => { const { data, error } = await sb.from('rapid_news').select('id,source_name,source_url,headline,summary,published_at,received_at,importance_score').order('importance_score', { ascending: false }).order('received_at', { ascending: false }).limit(100); if (error) { status.textContent = 'تعذر تحميل الأخبار الملتقطة'; return; } render(data || []); status.textContent = data?.length ? `${data.length} خبرًا محفوظًا` : 'بانتظار الأخبار الملتقطة'; };
  const refreshUnread = async () => { if (!currentUser) return; const { data, error } = await sb.rpc('rapid_news_unread_count'); if (!error) setBadge(Number(data || 0)); };
  const open = async () => { if (!window.mirsadViewAccess) return; const access = await window.mirsadViewAccess.openRapid(); if (!access.allowed) { status.textContent = access.error?.message === 'not_authenticated' ? 'سجّل الدخول لعرض الأخبار الملتقطة' : 'تعذر فتح الأخبار الملتقطة حاليًا'; await refreshUnread(); return; } opened = true; rail.hidden = false; toggle.setAttribute('aria-expanded', 'true'); status.textContent = access.unread_count ? `تم عرض ${access.unread_count} خبرًا جديدًا` : 'لا توجد أخبار جديدة غير مقروءة'; await refreshUnread(); };
  const consume = async (kind) => { if (!window.mirsadViewAccess) return false; more.disabled = true; all.disabled = true; const result = await window.mirsadViewAccess.consume(kind); more.disabled = false; all.disabled = false; if (!result.allowed) { const message = result.error?.message; status.textContent = message === 'not_authenticated' ? 'سجّل الدخول لاستخدام الفتحات' : (message ? 'تعذر تنفيذ العملية حاليًا' : 'لا توجد فتحات كافية'); return false; } status.textContent = result.charged ? `تم خصم ${kind === 'more' ? 5 : 100} فتحات` : 'الاستخدام مجاني في هذه الدورة'; return true; };
  more.addEventListener('click', async () => { if (!(await consume('more'))) return; visibleCount += 5; render(currentRows); });
  all.addEventListener('click', async () => { if (!(await consume('all'))) return; visibleCount = currentRows.length; render(currentRows); });
  toggle.addEventListener('click', () => { if (opened) { opened = false; rail.hidden = true; toggle.setAttribute('aria-expanded', 'false'); } else void open(); });
  const start = async () => { await load(); const { data: { session } } = await sb.auth.getSession(); currentUser = Boolean(session?.user); await refreshUnread(); channel = sb.channel('mirsad-rapid-news-live').on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'rapid_news' }, () => { void load(); void refreshUnread(); }).subscribe(); timer = setInterval(async () => { await load(); await refreshUnread(); }, 60000); };
  sb.auth.onAuthStateChange((_event, session) => { currentUser = Boolean(session?.user); if (currentUser) void refreshUnread(); else setBadge(0); });
  window.addEventListener('pagehide', () => { if (timer) clearInterval(timer); if (channel) sb.removeChannel(channel); });
  
  void start();
})();
