(() => {
  'use strict';
  const CONFIG={url:'https://dndlkenyfymlrjnslyzb.supabase.co',key:'sb_publishable_C92j3hFC-qVem_ncKHDf9Q_Ew970XUx'};
  const sb=window.supabase?.createClient?.(CONFIG.url,CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true}});const root=document.getElementById('wheelPage');let spinning=false;
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#039;'}[c]));
  const reasonCopy={vault_full:'الخزنة ممتلئة. اشحن لتحويل جزء منها لاحقًا.',daily_limit:'اكتملت سحبات اليوم.',slot_used:'هذه النافذة استُخدمت. عد في النافذة التالية.',cash_diverted:'رصيدك مرتفع أو غير محدود، لذلك تذهب الجائزة إلى الخزنة لا إلى الفتحات.','':'الفتحات النقدية من السحب محدودة يوميًا.'};
  const render=async()=>{if(!root||!sb)return;const {data,error}=await sb.rpc('get_wheel_status');if(error){root.innerHTML='<div class="wheel-shell"><section class="wheel-card"><div class="wheel-heading"><p class="wheel-kicker">مِرصاد</p><h1>سحب المكافأة</h1><p class="wheel-subtitle">تعذر تحميل الصفحة</p></div></section></div>';root.hidden=false;return}const s=Array.isArray(data)?data[0]:data;const values=s?.reward_values||[2,3,5,8,10,12,15,18,20,25,30,40,50,60,80,100],vault=Number(s?.vault_balance||0),cap=Number(s?.vault_cap||150),used=Number(s?.spins_today||0),limit=Number(s?.daily_spin_limit||3),spent=Number(s?.daily_payout_used||0),budget=Number(s?.daily_budget||8),reason=String(s?.reason||'');root.innerHTML=`<div class="wheel-shell"><header class="wheel-header"><div class="wheel-brand"><span class="wheel-brand-mark">◉</span><span>مِرصاد</span></div><button class="wheel-back" type="button" data-back>العودة</button></header><section class="wheel-card"><div class="wheel-heading"><p class="wheel-kicker">ترفيه محدود</p><h1>سحب المكافأة</h1><p class="wheel-subtitle">الرقم الظاهر على العجلة ليس كله رصيدًا قابلًا للإنفاق</p></div><div class="wheel-meta"><div class="wheel-stat">السحبات<strong>${used}/${limit}</strong></div><div class="wheel-stat">فتحات اليوم<strong>${spent}/${budget}</strong></div><div class="wheel-stat">الخزنة<strong>${vault.toLocaleString('ar')}</strong></div></div><div class="wheel-stage"><div class="wheel-pointer" aria-hidden="true"></div><div class="wheel" data-wheel role="img" aria-label="عجلة المكافآت">${values.map((v,i)=>`<div class="wheel-label" style="--angle:${i*(360/values.length)+360/(values.length*2)}deg"><span>${safe(v)}</span></div>`).join('')}</div></div><button class="mirsad-auth-button primary wheel-action" type="button" data-spin ${s?.can_spin?'':'disabled'}>${s?.can_spin?'اسحب الآن':reason==='vault_full'?'الخزنة ممتلئة':'غير متاح الآن'}</button>${reason==='vault_full'||reason==='cash_diverted'?'<button class="mirsad-auth-button wheel-action" type="button" data-billing style="margin-top:8px">شحن الرصيد</button>':''}<div class="wheel-status" data-status role="status" aria-live="polite">${safe(reasonCopy[reason]||reasonCopy[''])}</div><div class="wheel-bars"><div class="wheel-bar-label"><span>رصيد الخزنة غير قابل للإنفاق مباشرة</span><strong>${vault.toLocaleString('ar')} / ${cap.toLocaleString('ar')}</strong></div><div class="wheel-bar"><i style="width:${Math.min(100,vault/Math.max(1,cap)*100)}%"></i></div></div></section></div>`;root.hidden=false;root.querySelector('[data-back]')?.addEventListener('click',()=>{location.href='index.html'});root.querySelector('[data-billing]')?.addEventListener('click',()=>{location.href='billing.html'});root.querySelector('[data-spin]')?.addEventListener('click',()=>spin(values))};
  const spin=async(values)=>{if(spinning)return;const btn=root.querySelector('[data-spin]'),status=root.querySelector('[data-status]'),wheel=root.querySelector('[data-wheel]');spinning=true;btn.disabled=true;status.textContent='جارٍ السحب…';const {data,error}=await sb.rpc('spin_wheel');if(error){status.textContent='تعذر تنفيذ السحب، حاول مرة أخرى';btn.disabled=false;spinning=false;return}const r=Array.isArray(data)?data[0]:data;if(!r?.ok){status.textContent=reasonCopy[r?.error_code]||'غير متاح الآن';spinning=false;render();return}const list=values||[2,3,5,8,10,12,15,18,20,25,30,40,50,60,80,100],index=Math.max(0,list.indexOf(Number(r.reward_amount))),step=360/list.length,turns=5+Math.floor(Math.random()*2),offset=(360-(index*step+step/2)+360)%360;wheel.style.transform=`rotate(${turns*360+offset}deg)`;setTimeout(()=>{const cash=Number(r.daily_payout||0),vaultAmt=Number(r.vault_payout||0);status.innerHTML=cash>0?`أُضيف <strong>${safe(cash)}</strong> للرصيد، وذهب <strong>${safe(vaultAmt)}</strong> للخزنة`:`الجائزة الظاهرة <strong>${safe(r.reward_amount)}</strong> ذهبت للخزنة، لا إلى رصيد الإنفاق`;setTimeout(render,2200)},4300)};
  window.addEventListener('mirsad:authenticated',render,{once:true});setTimeout(render,1200);
})();
