(() => {
  'use strict';
  const CONFIG={url:'https://dndlkenyfymlrjnslyzb.supabase.co',key:'sb_publishable_C92j3hFC-qVem_ncKHDf9Q_Ew970XUx'};
  const sb=window.supabase?.createClient?.(CONFIG.url,CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true}});const root=document.getElementById('wheelPage');let spinning=false;
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const render=async()=>{if(!root||!sb)return;const {data,error}=await sb.rpc('get_wheel_status');if(error){root.innerHTML='<div class="wheel-shell"><section class="wheel-card"><div class="wheel-heading"><p class="wheel-kicker">مِرصاد</p><h1>سحب المكافأة</h1><p class="wheel-subtitle">تعذر تحميل الصفحة</p></div></section></div>';root.hidden=false;return}const s=Array.isArray(data)?data[0]:data;const values=s?.reward_values||[50,75,100,125,150,200,250,300,350,400,500,600,700,800,900,1000],vault=Number(s?.vault_balance||0),cap=Number(s?.vault_cap||10000),used=Number(s?.spins_today||0),spent=Number(s?.daily_payout_used||0),budget=Number(s?.daily_budget||300);root.innerHTML=`<div class="wheel-shell"><header class="wheel-header"><div class="wheel-brand"><span class="wheel-brand-mark">◉</span><span>مِرصاد</span></div><button class="wheel-back" type="button" data-back>العودة</button></header><section class="wheel-card"><div class="wheel-heading"><p class="wheel-kicker">مكافأتك اليومية</p><h1>سحب المكافأة</h1><p class="wheel-subtitle">اختَر لحظتك</p></div><div class="wheel-meta"><div class="wheel-stat">السحبات<strong>${used}/5</strong></div><div class="wheel-stat">اليوم<strong>${spent}/${budget}</strong></div><div class="wheel-stat">الخزنة<strong>${vault.toLocaleString('ar')}</strong></div></div><div class="wheel-stage"><div class="wheel-pointer" aria-hidden="true"></div><div class="wheel" data-wheel role="img" aria-label="عجلة المكافآت">${values.map((v,i)=>`<div class="wheel-label" style="--angle:${i*(360/values.length)+360/(values.length*2)}deg"><span>${safe(v)}</span></div>`).join('')}</div></div><button class="mirsad-auth-button primary wheel-action" type="button" data-spin ${s?.can_spin?'':'disabled'}>${s?.can_spin?'اسحب الآن':s?.reason==='vault_full'?'الخزنة ممتلئة':'غير متاح الآن'}</button><div class="wheel-status" data-status role="status" aria-live="polite">${s?.reason==='slot_used'?'عد في السحب القادم':s?.reason==='daily_limit'?'اكتملت سحبات اليوم':s?.reason==='vault_full'?'الخزنة ممتلئة':'حظًا موفقًا'}</div><div class="wheel-bars"><div class="wheel-bar-label"><span>رصيد الخزنة</span><strong>${vault.toLocaleString('ar')} / ${cap.toLocaleString('ar')}</strong></div><div class="wheel-bar"><i style="width:${Math.min(100,vault/cap*100)}%"></i></div></div></section></div>`;root.hidden=false;root.querySelector('[data-back]')?.addEventListener('click',()=>{location.href='index.html'});root.querySelector('[data-spin]')?.addEventListener('click',spin)};
  const spin=async()=>{if(spinning)return;const btn=root.querySelector('[data-spin]'),status=root.querySelector('[data-status]'),wheel=root.querySelector('[data-wheel]');spinning=true;btn.disabled=true;status.textContent='جارٍ السحب…';const {data,error}=await sb.rpc('spin_wheel');if(error){status.textContent='تعذر تنفيذ السحب، حاول مرة أخرى';btn.disabled=false;spinning=false;return}const r=Array.isArray(data)?data[0]:data;if(!r?.ok){status.textContent=r?.error_code==='vault_full'?'الخزنة ممتلئة':r?.error_code==='slot_used'?'تم استخدام هذه النافذة':'غير متاح الآن';spinning=false;return}const values=[50,75,100,125,150,200,250,300,350,400,500,600,700,800,900,1000],index=Math.max(0,values.indexOf(Number(r.reward_amount))),step=360/values.length,turns=5+Math.floor(Math.random()*2),offset=(360-(index*step+step/2)+360)%360;wheel.style.transform=`rotate(${turns*360+offset}deg)`;setTimeout(()=>{status.innerHTML=`مبروك، ربحت <strong>${safe(r.reward_amount)}</strong> فتحة`;setTimeout(render,1800)},4300)};
  window.addEventListener('mirsad:authenticated',render,{once:true});setTimeout(render,1200);
})();
