(() => {
  'use strict';
  const CONFIG={url:'https://dndlkenyfymlrjnslyzb.supabase.co',key:'sb_publishable_C92j3hFC-qVem_ncKHDf9Q_Ew970XUx'};
  const sb=window.supabase?.createClient?.(CONFIG.url,CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true}}); const root=document.getElementById('wheelPage'); let spinning=false;
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const render=async()=>{if(!root||!sb)return;const {data,error}=await sb.rpc('get_wheel_status');if(error){root.innerHTML='<div class="wheel-shell"><section class="wheel-card"><h1>سحب المكافأة</h1><p class="wheel-intro">تعذر تحميل حالة السحب الآن. حاول تحديث الصفحة.</p></section></div>';root.hidden=false;return}const s=Array.isArray(data)?data[0]:data;const values=s?.values||[50,75,100,150,200,250,350,500];const pity=Number(s?.pity_misses||0),vault=Number(s?.vault_balance||0),cap=Number(s?.vault_cap||10000),used=Number(s?.spins_today||0),budget=Number(s?.daily_budget||1000),spent=Number(s?.daily_payout_used||0);root.innerHTML=`<div class="wheel-shell"><header class="wheel-header"><div class="wheel-brand"><span aria-hidden="true">◉</span><span>مِرصاد</span></div><button class="wheel-back" type="button" data-back>العودة للأخبار</button></header><section class="wheel-card"><h1>سحب المكافأة</h1><p class="wheel-intro">خمس سحبات يومية، بأوزان محسوبة تلقائيًا وحماية من سوء الحظ.</p><div class="wheel-meta"><div class="wheel-stat">السحبات اليوم<strong>${used}/5</strong></div><div class="wheel-stat">المستخدم اليوم<strong>${spent}/${budget}</strong></div><div class="wheel-stat">عداد الحماية<strong>${pity}/20</strong></div></div><div class="wheel-stage"><div class="wheel-pointer" aria-hidden="true"></div><div class="wheel" data-wheel role="img" aria-label="عجلة مكافآت من ثماني خانات">${values.map((v,i)=>`<div class="wheel-label" style="--i:${i}"><span>${safe(v)}</span></div>`).join('')}</div></div><button class="mirsad-auth-button primary wheel-action" type="button" data-spin ${s?.can_spin?'':'disabled'}>${s?.can_spin?'اسحب الآن':s?.reason==='vault_full'?'الخزنة ممتلئة':'السحب غير متاح الآن'}</button><div class="wheel-status" data-status role="status" aria-live="polite">${s?.reason==='slot_used'?'هذه النافذة استُخدمت، عد في النافذة التالية.':s?.reason==='daily_limit'?'اكتملت سحبات اليوم.':s?.reason==='vault_full'?'الخزنة ممتلئة؛ يلزم تفريغها قبل السحب.':'الجوائز الأكبر أندر دائمًا، وحماية سوء الحظ ترفع الجوائز المتوسطة تدريجيًا.'}</div><div class="wheel-bars"><div class="wheel-bar-label"><span>الخزنة</span><strong>${vault.toLocaleString('ar')} / ${cap.toLocaleString('ar')}</strong></div><div class="wheel-bar"><i style="width:${Math.min(100,vault/cap*100)}%"></i></div></div><p class="wheel-note">الأوزان مبنية على <strong>v<sup>−α</sup></strong> بمتوسط مستهدف 200 فتحة للسحبة. بعد 10 سحبات دون جائزة متوسطة تبدأ الحماية تدريجيًا، وعند السحبة 20 تُضمن جائزة متوسطة دون رفع فرص الجوائز الكبرى.</p></section></div>`;root.hidden=false;root.querySelector('[data-back]')?.addEventListener('click',()=>{location.href='index.html'});root.querySelector('[data-spin]')?.addEventListener('click',spin)};
  const spin=async()=>{if(spinning)return;const btn=root.querySelector('[data-spin]'),status=root.querySelector('[data-status]'),wheel=root.querySelector('[data-wheel]');spinning=true;btn.disabled=true;status.textContent='جارٍ إجراء السحب بأمان…';const {data,error}=await sb.rpc('spin_wheel');if(error){status.textContent='تعذر تنفيذ السحب. حاول مرة أخرى.';btn.disabled=false;spinning=false;return}const r=Array.isArray(data)?data[0]:data;if(!r?.ok){status.textContent=r?.error_code==='vault_full'?'الخزنة ممتلئة؛ لا يمكن السحب حاليًا.':r?.error_code==='slot_used'?'هذه النافذة استُخدمت بالفعل.':'لا يمكن السحب الآن.';spinning=false;return}const values=[50,75,100,150,200,250,350,500],index=values.indexOf(Number(r.reward_amount)),target=index<0?0:index;const turns=5+Math.floor(Math.random()*2),offset=(360-(target*45+22.5)+360)%360;wheel.style.transform=`rotate(${turns*360+offset}deg)`;setTimeout(()=>{status.innerHTML=`مبروك! ربحت <strong>${safe(r.reward_amount)}</strong> فتحة. أضيف إلى رصيدك: <strong>${safe(r.daily_payout)}</strong>، وحُفظ في الخزنة: <strong>${safe(r.vault_payout)}</strong>.`;setTimeout(render,1800)},4300)};
  window.addEventListener('mirsad:authenticated',render,{once:true}); setTimeout(render,1200);
})();
