-- Add the remaining Arab countries to the independent country-news desk.
insert into public.arab_countries(name_ar,name_en,slug,flag_code,display_order)
values
  ('المغرب','Morocco','morocco','ma',1),
  ('تونس','Tunisia','tunisia','tn',3),
  ('ليبيا','Libya','libya','ly',4),
  ('السودان','Sudan','sudan','sd',6),
  ('موريتانيا','Mauritania','mauritania','mr',7),
  ('جيبوتي','Djibouti','djibouti','dj',8),
  ('جزر القمر','Comoros','comoros','km',9),
  ('الصومال','Somalia','somalia','so',10),
  ('فلسطين','Palestine','palestine','ps',11),
  ('الأردن','Jordan','jordan','jo',12),
  ('لبنان','Lebanon','lebanon','lb',13),
  ('سوريا','Syria','syria','sy',14),
  ('العراق','Iraq','iraq','iq',15),
  ('السعودية','Saudi Arabia','saudi-arabia','sa',16),
  ('عُمان','Oman','oman','om',18),
  ('الإمارات','United Arab Emirates','uae','ae',19),
  ('قطر','Qatar','qatar','qa',20),
  ('البحرين','Bahrain','bahrain','bh',21),
  ('الكويت','Kuwait','kuwait','kw',22)
on conflict (slug) do update set name_ar=excluded.name_ar,name_en=excluded.name_en,flag_code=excluded.flag_code,display_order=excluded.display_order,is_active=true,updated_at=now();
update public.arab_countries set display_order=2, updated_at=now() where slug='algeria';
update public.arab_countries set display_order=5, updated_at=now() where slug='egypt';
update public.arab_countries set display_order=17, updated_at=now() where slug='yemen';
insert into public.country_news_sources(country_id,source_key,source_name,source_url,feed_url,source_type,scope_keywords,priority,is_active,updated_at)
select c.id, v.source_key, v.source_name, v.source_url, v.feed_url, v.source_type, string_to_array(v.keywords, ','), v.priority, true, now()
from public.arab_countries c
join (values
  ('morocco','ma_hespress','هسبريس','https://www.hespress.com/','https://www.hespress.com/feed','local','المغرب,مغربي,مغربية,Morocco',1),
  ('morocco','ma_yabiladi','يابلادي','https://www.yabiladi.com/','https://www.yabiladi.com/rss/','local','المغرب,مغربي,Maroc,Morocco',2),
  ('morocco','ma_lematin','لو ماتان','https://www.lematin.ma/','https://www.lematin.ma/rss','local','المغرب,Maroc,Morocco',3),
  ('tunisia','tn_lapresse','لا براس','https://lapresse.tn/','https://lapresse.tn/feed/','local','تونس,تونسي,تونس,Tunisia',1),
  ('tunisia','tn_kapitalis','كابيتاليس','https://www.kapitalis.com/tunisie/','https://www.kapitalis.com/tunisie/feed/','local','تونس,تونسي,Tunisie',2),
  ('tunisia','tn_mosaique','موزاييك إف إم','https://www.mosaiquefm.net/','https://www.mosaiquefm.net/rss','local','تونس,تونسي,Tunisie',3),
  ('libya','ly_ahrar','ليبيا الأحرار','https://libyaalahrar.net/','https://libyaalahrar.net/feed/','local','ليبيا,ليبي,ليبية,Libya',1),
  ('libya','ly_akhbar','ليبيا أخبار','https://www.libyaakhbar.com/','https://www.libyaakhbar.com/feed/','local','ليبيا,ليبي,Libya',2),
  ('libya','ly_address','العنوان الليبي','https://www.addresslibya.com/','https://www.addresslibya.com/feed/','local','ليبيا,ليبي,Libya',3),
  ('sudan','sd_nilin','النيلين','https://www.alnilin.com/','https://www.alnilin.com/feed','local','السودان,سوداني,سودان,Sudan',1),
  ('sudan','sd_taghyeer','التغيير','https://www.altaghyeer.info/','https://www.altaghyeer.info/ar/feed','local','السودان,سوداني,الخرطوم',2),
  ('sudan','sd_post','سودان بوست','https://www.sudanspost.com/','https://www.sudanspost.com/feed/','local','Sudan,السودان,Khartoum',3),
  ('mauritania','mr_sahara','صحراء ميديا','https://www.saharamedias.net/','https://www.saharamedias.net/feed/','local','موريتانيا,نواكشوط,Mauritanie',1),
  ('mauritania','mr_cover','تغطية موريتانيا','https://news.google.com/search?q=%D9%85%D9%88%D8%B1%D9%8A%D8%AA%D8%A7%D9%86%D9%8A%D8%A7&hl=ar&gl=MR&ceid=MR:ar','https://news.google.com/rss/search?q=%D9%85%D9%88%D8%B1%D9%8A%D8%AA%D8%A7%D9%86%D9%8A%D8%A7&hl=ar&gl=MR&ceid=MR:ar','regional','موريتانيا,نواكشوط,Mauritania',2),
  ('mauritania','mr_nouakchott','تغطية نواكشوط','https://news.google.com/search?q=%D9%86%D9%88%D8%A7%D9%83%D8%B4%D9%88%D8%B7&hl=ar&gl=MR&ceid=MR:ar','https://news.google.com/rss/search?q=%D9%86%D9%88%D8%A7%D9%83%D8%B4%D9%88%D8%B7&hl=ar&gl=MR&ceid=MR:ar','regional','نواكشوط,موريتانيا',3),
  ('djibouti','dj_nation','لا ناسيون','https://www.lanation.dj/','https://www.lanation.dj/feed/','local','Djibouti,جيبوتي',1),
  ('djibouti','dj_cover','تغطية جيبوتي','https://news.google.com/search?q=%D8%AC%D9%8A%D8%A8%D9%88%D8%AA%D9%8A&hl=ar&gl=DJ&ceid=DJ:ar','https://news.google.com/rss/search?q=%D8%AC%D9%8A%D8%A8%D9%88%D8%AA%D9%8A&hl=ar&gl=DJ&ceid=DJ:ar','regional','جيبوتي,Djibouti',2),
  ('djibouti','dj_cover_en','تغطية Djibouti','https://news.google.com/search?q=Djibouti&hl=ar&gl=DJ&ceid=DJ:ar','https://news.google.com/rss/search?q=Djibouti&hl=ar&gl=DJ&ceid=DJ:ar','regional','Djibouti,جيبوتي',3),
  ('comoros','km_infos','كومور إنفو','https://www.comores-infos.net/','https://www.comores-infos.net/feed','local','Comores,القمر,Moroni',1),
  ('comoros','km_cover','تغطية جزر القمر','https://news.google.com/search?q=%D8%AC%D8%B2%D8%B1+%D8%A7%D9%84%D9%82%D9%85%D8%B1&hl=ar&gl=KM&ceid=KM:ar','https://news.google.com/rss/search?q=%D8%AC%D8%B2%D8%B1%20%D8%A7%D9%84%D9%82%D9%85%D8%B1&hl=ar&gl=KM&ceid=KM:ar','regional','القمر,جزر,Comoros',2),
  ('comoros','km_cover_en','تغطية Comoros','https://news.google.com/search?q=Comoros&hl=ar&gl=KM&ceid=KM:ar','https://news.google.com/rss/search?q=Comoros&hl=ar&gl=KM&ceid=KM:ar','regional','Comoros,القمر',3),
  ('somalia','so_goobjoog','قوبجوغ','https://goobjoog.com/','https://goobjoog.com/feed/','local','الصومال,مقديشو,Somalia',1),
  ('somalia','so_hiiraan','هيران','https://www.hiiraan.com/','https://www.hiiraan.com/rss.xml','local','Somalia,الصومال,Mogadishu',2),
  ('somalia','so_dalsan','راديو دلسان','https://www.radiodalsan.com/','https://www.radiodalsan.com/feed','local','Somalia,الصومال,Soomaaliya',3),
  ('palestine','ps_quds','القدس','https://qudsn.co/','https://qudsn.co/feed/','local','فلسطين,القدس,غزة,الضفة',1),
  ('palestine','ps_palinfo','المركز الفلسطيني للإعلام','https://www.palinfo.com/','https://www.palinfo.com/feed','local','فلسطين,غزة,القدس',2),
  ('palestine','ps_mem','مراقبة الشرق الأوسط','https://www.middleeastmonitor.com/','https://www.middleeastmonitor.com/feed/','regional','Palestine,Gaza,فلسطين,غزة',3),
  ('jordan','jo_ghad','الغد','https://alghad.com/','https://alghad.com/rss','local','الأردن,اردن,عمان,Jordan',1),
  ('jordan','jo_roya','رؤيا','https://royanews.tv/','https://royanews.tv/rss','local','الأردن,اردن,عمان',2),
  ('jordan','jo_cover','تغطية الأردن','https://news.google.com/search?q=%D8%A7%D9%84%D8%A3%D8%B1%D8%AF%D9%86&hl=ar&gl=JO&ceid=JO:ar','https://news.google.com/rss/search?q=%D8%A7%D9%84%D8%A3%D8%B1%D8%AF%D9%86&hl=ar&gl=JO&ceid=JO:ar','regional','الأردن,اردن,عمان,Jordan',3),
  ('lebanon','lb_24','النهار','https://www.annahar.com/','https://www.annahar.com/rss','local','لبنان,لبناني,بيروت',1),
  ('lebanon','lb_lbc','ليبانيوز','https://libnanews.com/','https://libnanews.com/feed','local','Liban,Lebanon,لبنان',2),
  ('lebanon','lb_cover','تغطية لبنان','https://news.google.com/search?q=%D9%84%D8%A8%D9%86%D8%A7%D9%86&hl=ar&gl=LB&ceid=LB:ar','https://news.google.com/rss/search?q=%D9%84%D8%A8%D9%86%D8%A7%D9%86&hl=ar&gl=LB&ceid=LB:ar','regional','لبنان,بيروت,Lebanon',3),
  ('syria','sy_enab','عنب بلدي','https://www.enabbaladi.net/','https://www.enabbaladi.net/feed/','local','سوريا,سوري,دمشق',1),
  ('syria','sy_sana','سانا','https://www.sana.sy/','https://www.sana.sy/?feed=rss2','official','سوريا,سوري,دمشق',2),
  ('syria','sy_npa','نورث برس','https://npasyria.com/','https://npasyria.com/feed/','local','سوريا,سوري,حلب',3),
  ('iraq','iq_sumaria','بغداد اليوم','https://baghdadtoday.news/','https://baghdadtoday.news/rss','local','العراق,عراقي,بغداد',1),
  ('iraq','iq_nas','عراقي نيوز','https://www.iraqinews.com/','https://www.iraqinews.com/feed','local','Iraq,العراق,Baghdad',2),
  ('iraq','iq_cover','تغطية العراق','https://news.google.com/search?q=%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82&hl=ar&gl=IQ&ceid=IQ:ar','https://news.google.com/rss/search?q=%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82&hl=ar&gl=IQ&ceid=IQ:ar','regional','العراق,بغداد,Iraq',3),
  ('saudi-arabia','sa_aawsat','الشرق الأوسط','https://english.aawsat.com/','https://english.aawsat.com/feed','local','Saudi,السعودية,الرياض',1),
  ('saudi-arabia','sa_cover','تغطية السعودية','https://news.google.com/search?q=%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9&hl=ar&gl=SA&ceid=SA:ar','https://news.google.com/rss/search?q=%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9&hl=ar&gl=SA&ceid=SA:ar','regional','السعودية,الرياض,Saudi',2),
  ('saudi-arabia','sa_cover_en','تغطية Saudi Arabia','https://news.google.com/search?q=Saudi%20Arabia&hl=ar&gl=SA&ceid=SA:ar','https://news.google.com/rss/search?q=Saudi%20Arabia&hl=ar&gl=SA&ceid=SA:ar','regional','Saudi,السعودية,Riyadh',3),
  ('oman','om_times','تايمز أوف عمان','https://timesofoman.com/','https://timesofoman.com/feed','local','Oman,عمان,مسقط',1),
  ('oman','om_observer','عمان أوبزرفر','https://www.omanobserver.om/','https://www.omanobserver.om/rss','local','Oman,عمان,Muscat',2),
  ('oman','om_stories','أرابيان ستوريز','https://www.thearabianstories.com/','https://www.thearabianstories.com/feed','local','Oman,عمان,Muscat',3),
  ('uae','ae_gulfnews','غلف نيوز','https://gulfnews.com/','https://gulfnews.com/feed','local','Emirates,UAE,الإمارات,دبي',1),
  ('uae','ae_today','غلف توداي','https://www.gulftoday.ae/','https://www.gulftoday.ae/rss','local','Emirates,UAE,الإمارات,دبي',2),
  ('uae','ae_cover','تغطية الإمارات','https://news.google.com/search?q=%D8%A7%D9%84%D8%A5%D9%85%D8%A7%D8%B1%D8%A7%D8%AA&hl=ar&gl=AE&ceid=AE:ar','https://news.google.com/rss/search?q=%D8%A7%D9%84%D8%A5%D9%85%D8%A7%D8%B1%D8%A7%D8%AA&hl=ar&gl=AE&ceid=AE:ar','regional','الإمارات,دبي,أبوظبي',3),
  ('qatar','qa_tribune','دوحة نيوز','https://dohanews.co/','https://dohanews.co/feed','local','Qatar,قطر,الدوحة,Doha',1),
  ('qatar','qa_gulf','مرحبا قطر','https://marhaba.qa/','https://marhaba.qa/feed','local','Qatar,قطر,Doha',2),
  ('qatar','qa_cover','تغطية قطر','https://news.google.com/search?q=%D9%82%D8%B7%D8%B1&hl=ar&gl=QA&ceid=QA:ar','https://news.google.com/rss/search?q=%D9%82%D8%B7%D8%B1&hl=ar&gl=QA&ceid=QA:ar','regional','قطر,الدوحة,Qatar',3),
  ('bahrain','bh_bilad','البلاد','https://www.albiladpress.com/','https://www.albiladpress.com/rss','local','البحرين,بحرين,المنامة',1),
  ('bahrain','bh_watan','الوطن','https://www.alwatannews.net/','https://www.alwatannews.net/rss','local','البحرين,بحرين,المنامة',2),
  ('bahrain','bh_cover','تغطية البحرين','https://news.google.com/search?q=%D8%A7%D9%84%D8%A8%D8%AD%D8%B1%D9%8A%D9%86&hl=ar&gl=BH&ceid=BH:ar','https://news.google.com/rss/search?q=%D8%A7%D9%84%D8%A8%D8%AD%D8%B1%D9%8A%D9%86&hl=ar&gl=BH&ceid=BH:ar','regional','البحرين,المنامة,Bahrain',3),
  ('kuwait','kw_jarida','تايمز الكويت','https://timeskuwait.com/','https://timeskuwait.com/feed/','local','Kuwait,الكويت',1),
  ('kuwait','kw_cover','تغطية الكويت','https://news.google.com/search?q=%D8%A7%D9%84%D9%83%D9%88%D9%8A%D8%AA&hl=ar&gl=KW&ceid=KW:ar','https://news.google.com/rss/search?q=%D8%A7%D9%84%D9%83%D9%88%D9%8A%D8%AA&hl=ar&gl=KW&ceid=KW:ar','regional','الكويت,Kuwait',2),
  ('kuwait','kw_cover_en','تغطية Kuwait','https://news.google.com/search?q=Kuwait&hl=ar&gl=KW&ceid=KW:ar','https://news.google.com/rss/search?q=Kuwait&hl=ar&gl=KW&ceid=KW:ar','regional','Kuwait,الكويت',3)
) as v(slug,source_key,source_name,source_url,feed_url,source_type,keywords,priority) on v.slug=c.slug
on conflict (source_key) do update set country_id=excluded.country_id,source_name=excluded.source_name,source_url=excluded.source_url,feed_url=excluded.feed_url,source_type=excluded.source_type,scope_keywords=excluded.scope_keywords,priority=excluded.priority,is_active=true,updated_at=now();
